[build]
  command = "npm ci --omit=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_INCLUDE = "dev"
  NPM_CONFIG_OMIT = "optional"
  ROLLUP_NO_NATIVE = "true"
  ESBUILD_BINARY_PATH = "/usr/bin/esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200