[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_OPTIONAL = "false"
  SKIP_OPTIONAL_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200