[build]
  command = "rm -rf node_modules package-lock.json && npm install --omit=optional --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_INCLUDE = "dev"
  NPM_CONFIG_OMIT = "optional"
  ROLLUP_NO_NATIVE = "true"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200